services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: healthNexaServer
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env.docker
    volumes:
      - ./server:/server
      - /server/node_modules
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: healthNexaClient
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      - ./client:/client
      - /client/node_modules
    
  mongo:
    image: mongo:7
    container_name: healthNexa_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - healthNexa_mongo_data:/data/db
      
  redis:
    image: redis:7-alpine
    container_name: healthNexa_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - healthNexa_redis_data:/data
      
  redisinsight:
    image: redis/redisinsight:latest
    container_name: healthNexa_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - healthNexa_redisinsight_data:/data
      
volumes:
  healthNexa_mongo_data:
  healthNexa_redis_data:
  healthNexa_redisinsight_data: